export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS"; 
export const CLEAR_ERRORS = "CLEAR_ERRORS"; 

export const FETCH_SHOE_LOADING = "FETCH_SHOE_LOADING";
export const FETCH_SHOE_FAILED = "FETCH_SHOE_FAILED";
export const FETCH_SHOE_SUCCESS = "FETCH_SHOE_SUCCESS";

export const FETCH_SHOES_LOADING = "FETCH_SHOES_LOADING";
export const FETCH_SHOES_FAILED = "FETCH_SHOES_FAILED";
export const FETCH_SHOES_SUCCESS = "FETCH_SHOESSUCCESS";

export const FETCH_BASKET_LOADING = "FETCH_BASKET_LOADING";
export const FETCH_BASKET_FAILED = "FETCH_BASKET_FAILED";
export const FETCH_BASKET_SUCCESS = "FETCH_BASKET_SUCCESS";

export const FETCH_FAVORITES_FAILED = "FETCH_FAVORITES_FAILED";
export const FETCH_FAVORITES_LOADING = "FETCH_FAVORITES_LOADING";
export const FETCH_FAVORITES_SUCCESS = "FETCH_FAVORITES_SUCCESS";

export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const ADD_TO_BASKET_REQUEST = "ADD_TO_BASKET_REQUEST";

export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";


export const BUY_PRODUCT_FAILED = "BUY_PRODUCT_FAILED";
export const BUY_PRODUCT_SUCCESS = "BUY_PRODUCT_SUCCESS";

export const CLEAN_USER_DATA = "CLEAN_USER_DATA";

